name: weather_forecast_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  theme_manager: ^1.1.1
  flutter:
    sdk: flutter
  adaptive_theme: ^3.4.0
  get: ^4.6.6
    


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
  - res/icons/splashogo.png
  - res/icons/planning.png
  uses-material-design: true
